test_that("fwi_01", {
  library(data.table)
  test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
  actual <- fwi(test_fwi)
  expected <- read.csv("../data/fwi_01.csv")
  test_columns(actual, expected)
  expect_equal(actual, expected)
})
test_that("fwi_02", {
  library(data.table)
  test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
  actual <- fwi(test_fwi, out="all")
  expected <- read.csv("../data/fwi_02.csv")
  test_columns(actual, expected)
  expect_equal(actual, expected)
})
test_that("fwi_03", {
  library(data.table)
  test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
  actual <- fwi(test_fwi, out="fwi")
  expected <- read.csv("../data/fwi_03.csv")
  test_columns(actual, expected)
  expect_equal(actual, expected)
})
test_that("fwi_04", {
  library(data.table)
  test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
  actual <- fwi(test_fwi, init=data.frame(ffmc=85, dmc=6, dc=15, lat=55))
  expected <- read.csv("../data/fwi_04.csv")
  test_columns(actual, expected)
  expect_equal(actual, expected)
})
test_that("fwi_05", {
  library(data.table)
  test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
  actual <- fwi(test_fwi, init=data.frame(ffmc=0, dmc=0, dc=0, lat=55))
  expected <- read.csv("../data/fwi_05.csv")
  test_columns(actual, expected)
  expect_equal(actual, expected)
})
# test_that("fwi_06", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   actual <- fwi(test_fwi, init=data.frame(ffmc=200, dmc=1000, dc=10000, lat=55))
#   expected <- read.csv("../data/fwi_06.csv")
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
# test_that("fwi_07", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   actual <- fwi(test_fwi, lat.adjust = FALSE)
#   expected <- read.csv("../data/fwi_07.csv")
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
# test_that("fwi_08", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   actual <- fwi(test_fwi, uppercase = FALSE)
#   expected <- read.csv("../data/fwi_08.csv")
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
# test_that("fwi_09", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   actual <- fwi(test_fwi[7,])
#   expected <- read.csv("../data/fwi_09.csv")
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
# test_that("fwi_10", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   expected <- read.csv("../data/fwi_10.csv")
#   actual <- fwi(test_fwi[8:13,])
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
# test_that("fwi_11", {
#   library(data.table)
#   test_fwi <- read.csv('../../data/test_fwi.csv', sep=';')
#   expected <- read.csv("../data/fwi_11.csv")
#   actual <- fwi(test_fwi, batch = FALSE)
#   test_columns(actual, expected)
#   expect_equal(actual, expected)
# })
