library(cffdrs)
  test_that("fbp", {
  data("test_fbp")
  expect_equal(as.character(fbp(test_fbp)), as.character(read.csv(".//tests/data/fbp_01.csv")))
  expect_equal(as.character(fbp(test_fbp,output="Primary")), as.character(read.csv(".//tests/data/fbp_02.csv")))
  expect_equal(as.character(fbp(test_fbp,"P")), as.character(read.csv(".//tests/data/fbp_03.csv")))
  expect_equal(as.character(fbp(test_fbp,"Secondary")), as.character(read.csv(".//tests/data/fbp_04.csv")))
  expect_equal(as.character(fbp(test_fbp,"S")), as.character(read.csv(".//tests/data/fbp_05.csv")))
  expect_equal(as.character(fbp(test_fbp,"All")), as.character(read.csv(".//tests/data/fbp_06.csv")))
  expect_equal(as.character(fbp(test_fbp,"A")), as.character(read.csv(".//tests/data/fbp_07.csv")))
  expect_equal(as.character(fbp(test_fbp[7,])), as.character(read.csv(".//tests/data/fbp_08.csv")))
  expect_equal(as.character(fbp(test_fbp[8:13,])), as.character(read.csv(".//tests/data/fbp_09.csv")))
  expect_equal(as.character(fbp()), as.character(read.csv(".//tests/data/fbp_10.csv")))
})
